# Generated by Django 3.0.3 on 2020-03-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200216_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainapp.Recipe'),
        ),
        migrations.AddConstraint(
            model_name='userholding',
            constraint=models.CheckConstraint(check=models.Q(amount__gte=0), name='amount_gte_0'),
        ),
    ]
